### ISSUE TITLE
[FEAT]: Add Symbols of Other Currencies

### ISSUE THREAD

**Issue by SaketKaswa20** [SaketKaswa20/Forex_Converter_WebApp#1]
Add Symbol of Other Currencies which are not in the WebApp

**Comment by Phil94comp** [comment]
I am working on the issue and I have a question. When adding the currency symbols if a country has the same currency symbol as another country in the list should I skip it?

**Comment by SaketKaswa20** [comment]
No, add it again to that specific country again.

**Comment by Phil94comp** [comment]
I just submitted a pull request. Please let me know if you like the changes. I have a link below to the website I used for the list of country currency codes.

https://www.worlddata.info/currencies/

**Comment by SaketKaswa20** [comment]
Closed by #2
